module.exports = (sequelize, DataTypes) => {
    const MembershipFormSubmission = sequelize.define('MembershipFormSubmission', {
      user_id: {
        
        type: DataTypes.INTEGER,
        allowNull: false,
      },
      last_name: DataTypes.STRING,
      first_name: DataTypes.STRING,
      middle_name: DataTypes.STRING,
      suffix: DataTypes.STRING,
      civil_status: DataTypes.STRING,
      gender: DataTypes.STRING,
      weight: DataTypes.FLOAT,
      height: DataTypes.FLOAT,
      date_of_birth: DataTypes.DATEONLY,
      age: DataTypes.INTEGER,
      tin: DataTypes.STRING,
      religion: DataTypes.STRING,
      household_size: DataTypes.INTEGER,
      sss: DataTypes.STRING,
      philhealth: DataTypes.STRING,
      umid: DataTypes.STRING,
      pag_ibig: DataTypes.STRING,
      philsys_id: DataTypes.STRING,
      passport_id: DataTypes.STRING,
      other_id: DataTypes.STRING,
      highest_education: DataTypes.STRING,
      school_last_attended: DataTypes.STRING,
      present_house_no: DataTypes.STRING,
      present_barangay: DataTypes.STRING,
      present_municipality: DataTypes.STRING,
      present_province: DataTypes.STRING,
      present_zip_code: DataTypes.STRING,
      permanent_house_no: DataTypes.STRING,
      permanent_barangay: DataTypes.STRING,
      permanent_municipality: DataTypes.STRING,
      permanent_province: DataTypes.STRING,
      permanent_zip_code: DataTypes.STRING,
      residence_ownership: DataTypes.STRING,
      mobile_number: DataTypes.STRING,
      email: DataTypes.STRING,
      facebook: DataTypes.STRING,
      occupation: DataTypes.STRING,
      employer: DataTypes.STRING,
      job_title: DataTypes.STRING,
      employer_contact: DataTypes.STRING,
      date_hired: DataTypes.DATEONLY,
      employer_address: DataTypes.STRING,
      monthly_income: DataTypes.FLOAT,
      employment_status: DataTypes.STRING,
      business_name: DataTypes.STRING,
      business_address: DataTypes.STRING,
      business_owners: DataTypes.STRING,
      self_employed: DataTypes.STRING,
      business_product: DataTypes.STRING,
      business_monthly_income: DataTypes.FLOAT,
      spouse_last_name: DataTypes.STRING,
      spouse_first_name: DataTypes.STRING,
      spouse_middle_name: DataTypes.STRING,
      spouse_suffix: DataTypes.STRING,
      spouse_date_of_birth: DataTypes.DATEONLY,
      spouse_occupation: DataTypes.STRING,
      spouse_monthly_income: DataTypes.FLOAT,
      spouse_other_income: DataTypes.FLOAT,
      spouse_father_name: DataTypes.STRING,
      spouse_mother_name: DataTypes.STRING,
      spouse_mobile_number: DataTypes.STRING,
      spouse_employer: DataTypes.STRING,
      spouse_employer_contact: DataTypes.STRING,
      spouse_employer_address: DataTypes.STRING,
      spouse_employment_status: DataTypes.STRING,
      spouse_job_title: DataTypes.STRING,
      spouse_date_hired: DataTypes.DATEONLY,
      beneficiary1_name: DataTypes.STRING,
      beneficiary1_birthdate: DataTypes.DATEONLY,
      beneficiary1_relationship: DataTypes.STRING,
      beneficiary2_name: DataTypes.STRING,
      beneficiary2_birthdate: DataTypes.DATEONLY,
      beneficiary2_relationship: DataTypes.STRING,
      beneficiary3_name: DataTypes.STRING,
      beneficiary3_birthdate: DataTypes.DATEONLY,
      beneficiary3_relationship: DataTypes.STRING,
      recruiter_name: DataTypes.STRING,
      recruiter_address: DataTypes.STRING,
      recruiter_pb_no: DataTypes.STRING,
      agree_terms: DataTypes.BOOLEAN,
      status: DataTypes.STRING
    });
  
    return MembershipFormSubmission;
  };
  
  //MembershipFormSubmission.js